changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]

  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature

    - title: "🐛 Fixes"
      labels:
        - bug
        - fix

    - title: "🔒 Security"
      labels:
        - security

    - title: "📚 Documentation"
      labels:
        - documentation

    - title: "🧰 Maintenance"
      labels:
        - dependencies
        - chore
        - ci

    - title: "Other Changes"
      labels:
        - "*"
