spring:
  config:
    activate:
      on-profile: test
  flyway:
    validate-on-migrate: true

app:
  data-encryption:
    allow-ephemeral-key: true
  clamav:
    enabled: false

logging:
  file:
    name: ""

management:
  endpoint:
    health:
      validate-group-membership: false
